FROM nginx:1.31.3-alpine-slim

LABEL maintainer="Sandeep Kumar"
LABEL description="This is BUs Ticket Booking Platform built on nginx"

WORKDIR /usr/share/nginx/html

EXPOSE 80

COPY index.html .