FROM httpd:2.4.68-alpine

LABEL maintainer="Sandeep Kumar"
LABEL description="This is a movie tickets booking platform built on httpd"

WORKDIR /usr/local/apache2/htdocs/

EXPOSE 80

COPY index.html .